name: Frontend CI (Blinkit)

on:
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # ✅ Fix Node version
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # ✅ Clean install
      - run: npm ci

      # ✅ Build with ENV
      - name: Build frontend
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
